config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :cgus
  resources :mentionslegales
  resources :faqs
  resources :contacts
  resources :freelances
  resources :portfolios
  resources :resumes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/controllers/cgus_controller.rb
class CgusController < ApplicationController
  before_action :set_cgu, only: [:show, :edit, :update, :destroy]

  # GET /cgus
  # GET /cgus.json
  def index
    @cgus = Cgu.all
  end

  # GET /cgus/1
  # GET /cgus/1.json
  def show
  end

  # GET /cgus/new
  def new
    @cgu = Cgu.new
  end

  # GET /cgus/1/edit
  def edit
  end

  # POST /cgus
  # POST /cgus.json
  def create
    @cgu = Cgu.new(cgu_params)

    respond_to do |format|
      if @cgu.save
        format.html { redirect_to @cgu, notice: 'Cgu was successfully created.' }
        format.json { render :show, status: :created, location: @cgu }
      else
        format.html { render :new }
        format.json { render json: @cgu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cgus/1
  # PATCH/PUT /cgus/1.json
  def update
    respond_to do |format|
      if @cgu.update(cgu_params)
        format.html { redirect_to @cgu, notice: 'Cgu was successfully updated.' }
        format.json { render :show, status: :ok, location: @cgu }
      else
        format.html { render :edit }
        format.json { render json: @cgu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cgus/1
  # DELETE /cgus/1.json
  def destroy
    @cgu.destroy
    respond_to do |format|
      format.html { redirect_to cgus_url, notice: 'Cgu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cgu
      @cgu = Cgu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cgu_params
      params.fetch(:cgu, {})
    end
end

app/helpers/cgus_helper.rb
module CgusHelper
end

app/views/cgus/_form.html.erb
<%= form_with(model: cgu, local: true) do |form| %>
  <% if cgu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cgu.errors.count, "error") %> prohibited this cgu from being saved:</h2>

      <ul>
      <% cgu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cgus/edit.html.erb
<h1>Editing Cgu</h1>

<%= render 'form', cgu: @cgu %>

<%= link_to 'Show', @cgu %> |
<%= link_to 'Back', cgus_path %>

app/views/cgus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cgus</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cgus.each do |cgu| %>
      <tr>
        <td><%= link_to 'Show', cgu %></td>
        <td><%= link_to 'Edit', edit_cgu_path(cgu) %></td>
        <td><%= link_to 'Destroy', cgu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cgu', new_cgu_path %>

app/views/cgus/new.html.erb
<h1>New Cgu</h1>

<%= render 'form', cgu: @cgu %>

<%= link_to 'Back', cgus_path %>

app/views/cgus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cgu_path(@cgu) %> |
<%= link_to 'Back', cgus_path %>